### ISSUE TITLE
Unsafe thread pool

### ISSUE THREAD

**Issue by Ceniza666** [valerioformato/RTIAW#1]
When waiting for the thread pool to finish, the code sleeps for a few milliseconds and checks if the pool is empty. The check will start to return true the moment the last task is popped, but right before the last task begins execution. If the code is changed to process full rows instead of single pixels (which uses less memory), there’s a high chance the code will crash because it will see the thread pool as empty, even though there’s likely at least one worker thread still active.
What is needed is a check that indicates the thread pool is not busy (empty with no running tasks).

**Comment by Spongman** [comment]
better yet, just use `boost/asio/thread_pool.hpp`

**Comment by valerioformato** [comment]
> better yet, just use `boost/asio/thread_pool.hpp`

That's possible indeed but, since boost tends to be quite a big dependency to bring in a project, I prefer to wait to see if there is any other boost module that could be used.

**Comment by web2098** [comment]
Since your thread pool returns a future for each task submitted the renderer thread could wait for each future to be marked as complete instead sleeping.

**Comment by valerioformato** [comment]
> Since your thread pool returns a future for each task submitted the renderer thread could wait for each future to be marked as complete instead sleeping.

That's a good point, I'll take a look during the weekend and see if this could be abstracted easily.

**Comment by valerioformato** [comment]
Closed by PR #4
